local util = require "util"

local function gen_protocol_tag(ast, namespace)
    local tags = {}
    for k,v in pairs(ast) do
        tags[#tags + 1] = {
            name = k,
            value  = v.tag,
        }
    end
    table.sort(tags, function (a, b) return a.name < b.name end)

    local output = "-- Generated by sprotodump. DO NOT EDIT!\n"
    output = output .. ("%s = {\n"):format(namespace)
    for _, tag in ipairs(tags) do
        output = output .. ("\t%s = %s,\n"):format(tag.name, tag.value)
    end
    output = output .. "}\n"
    return output
end

local function main(trunk, build, param)
    local outfile = param.outfile
    local out = gen_protocol_tag(build.protocol, param.package)
    util.write_file(outfile, out, "w")
end

return main
